{
 "title": "Buddy",
 "time": { "from": "2023-04-02T16:02:06.657Z", "to": "2023-04-02T16:33:30.528Z" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_print_speed, printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_model)(prusa_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_model}}"
    }
   ]
  },
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Number of files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_files{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_storage}}"
    }
   ]
  },
  {
   "title": "PrusaLink",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_text}}"
    }
   ]
  },
  {
   "title": "Printer server ver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_server}}"
    }
   ]
  },
  { "title": "Printing progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Name of printed file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing{printer_name=\"$printer\"} == 1",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printing progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Actual printing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_print_time{printer_name=\"$printer\"} )",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printing time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing_time_remaining{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  { "title": "Printer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Target bed temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_bed_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target nozzle temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_nozzle_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_print_speed{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Z Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_z_height{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chosen Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_filament)(prusa_material{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Filepath",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (printer_job_path)(prusa_material{printer_name=\"$printer\", printer_job_path!=\"\"})",
     "legendFormat": "{{printer_job_path}}"
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_bed_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_nozzle_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Z Height in time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_z_height{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing progress in time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}