{
 "title": "Prusa Buddy Dashboard",
 "description": "This is dashboard for monitoring Prusa Buddy based 3D printers with use of pubeldev/prusa_exporter",
 "time": { "from": "2024-02-11T13:03:53.179Z", "to": "2024-02-11T13:53:24.102Z" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_buddy_info,printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_nozzle_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_bed_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target bed"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_fan_print{printer_name=\"$printer\"})",
     "legendFormat": "Print fan"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_fan_hotend{printer_name=\"$printer\"})",
     "legendFormat": "Hotend fan"
    }
   ]
  },
  {
   "title": "Printing progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Actual printing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_print_time{printer_name=\"$printer\"} )",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printing time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_printing_time_remaining{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Loaded filament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_filament)(prusa_buddy_material{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Name of printed file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_buddy_printing{printer_name=\"$printer\"} == 1",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Z Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_z_height{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pritner_state, printer_name)(prusa_buddy_status{printer_name=\"$printer\"}) ",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_buddy_version{printer_name=\"$printer\"}) by (printer_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_print_speed_ratio{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_nozzle_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_bed_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Printer Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target temp success",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_nozzle_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_buddy_nozzle_target_temperature{printer_name=\"$printer\"})",
       "legendFormat": "Nozzle"
      },
      {
       "expr": "max by (printer_name)(prusa_buddy_bed_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_buddy_bed_target_temperature{printer_name=\"$printer\"})",
       "legendFormat": "Bed"
      }
     ]
    },
    {
     "title": "IP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_buddy_version{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_address}}"
      }
     ]
    },
    {
     "title": "Axis positions",
     "type": "stat",
     "description": "While printing printer returns unfortunately 0 but z axis",
     "gridPos": { "h": 4, "w": 9, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_axis_x{printer_name=\"$printer\"}) ",
       "legendFormat": "X"
      },
      {
       "expr": "max by (printer_name)(prusa_buddy_axis_y{printer_name=\"$printer\"}) ",
       "legendFormat": "Y"
      },
      {
       "expr": "max by (printer_name)(prusa_buddy_axis_z{printer_name=\"$printer\"}) ",
       "legendFormat": "Z"
      }
     ]
    },
    {
     "title": "PrusaLink type",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_buddy_version{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_text}}"
      }
     ]
    },
    {
     "title": "Prusa Link ver",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_buddy_version{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_server}}"
      }
     ]
    },
    {
     "title": "Number of files",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_buddy_files{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_storage}}"
      }
     ]
    },
    {
     "title": "MMU status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 2, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_mmu{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filepath",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 5, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max by (printer_job_path)(prusa_buddy_material{printer_name=\"$printer\", printer_job_path!=\"\"})",
       "legendFormat": "{{printer_job_path}}"
      }
     ]
    },
    {
     "title": "Printing progress in time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_printing_progress{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fan speeds",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_fan_print{printer_name=\"$printer\"})",
       "legendFormat": "Print fan"
      },
      {
       "expr": "max by (printer_name)(prusa_buddy_fan_hotend{printer_name=\"$printer\"})",
       "legendFormat": "Hotend fan"
      }
     ]
    },
    {
     "title": "Z Height in time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_buddy_z_height{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Printer Detail - SYSLOG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Active Extruder",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name) (prusa_buddy_active_extruder{printer_name=\"$printer\"}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heater Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_heater_enabled{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjustment of Z Axis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name) (prusa_buddy_axis_z_adjustment{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buddy BOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name, buddy_bom, buddy_revision)(prusa_buddy_syslog_info{printer_name=\"$printer\"})",
     "legendFormat": "{{buddy_bom}}"
    }
   ]
  },
  {
   "title": "Buddy revision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name, buddy_bom, buddy_revision)(prusa_buddy_syslog_info{printer_name=\"$printer\"})",
     "legendFormat": "{{buddy_bom}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_cpu_usage_ratio{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- max by (printer_name)(prusa_buddy_heap_free{printer_name=\"$printer\"}) / max by (printer_name)(prusa_buddy_heap_total{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_24volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - 24V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - 5V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_bed{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - heatbed"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_nozzle{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - nozzle"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_sandwich_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - sandwich 5V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_splitter_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - splitter 5V"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_cpu_usage_ratio{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_heap_total{printer_name=\"$printer\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_heap_total{printer_name=\"$printer\"}) - max by (printer_name)(prusa_buddy_heap_free{printer_name=\"$printer\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_current_input{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - input"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_current_mmu{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - mmu"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_current_nozzle{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - nozzle"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_current_xlbuddy_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - xlBuddy 5V current"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_current_bed{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - heatbed rail - {{rail}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_24volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - 24V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - 5V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_bed{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - heatbed"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_nozzle{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - nozzle"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_sandwich_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - sandwich 5V"
    },
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_voltage_splitter_5volts{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - splitter 5V"
    }
   ]
  },
  {
   "title": "Loadcell data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_loadcell_hysteresis{printer_name=\"$printer\"})",
     "legendFormat": "Hysteresis"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_loadcell_scale{printer_name=\"$printer\"})",
     "legendFormat": "Scale"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_loadcell_threshold{printer_name=\"$printer\"})",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "Points dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_points_dropped{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media prefetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name,rail)(prusa_buddy_media_prefetched{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Overcurrent detection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_overcurrent_input{printer_name=\"$printer\"})",
     "legendFormat": "Hysteresis"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_overcurrent_nozzle{printer_name=\"$printer\"})",
     "legendFormat": "Scale"
    }
   ]
  },
  {
   "title": "Dwarf temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_buddy_dwarf_board_temp{printer_name=\"$printer\"})",
     "legendFormat": "Board"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_dwarf_mcu_temp{printer_name=\"$printer\"})",
     "legendFormat": "MCU"
    }
   ]
  }
 ]
}