{
 "title": "Prusa Einsy Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_einsy_info,printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_nozzle_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_einsy_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_einsy_bed_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_einsy_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target bed"
    }
   ]
  },
  {
   "title": "Nozzle size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_nozzle_size{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Actual printing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_print_time{printer_name=\"$printer\"} )",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printing time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_printing_time_remaining{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Loaded filament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_filament)(prusa_einsy_material{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Name of printed file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_einsy_printing{printer_name=\"$printer\"} == 1",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Z Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_axis_z{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pritner_state, printer_name)(prusa_einsy_status{printer_name=\"$printer\"}) ",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_einsy_info{printer_name=\"$printer\"}) by (printer_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer location",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_location)(prusa_einsy_info{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_location}}"
    }
   ]
  },
  {
   "title": "Printer speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_print_speed_ratio{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_nozzle_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_einsy_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_einsy_bed_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_einsy_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Printer Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Axis position",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_einsy_axis_x{printer_name=\"$printer\"}",
       "legendFormat": "X"
      },
      {
       "expr": "prusa_einsy_axis_y{printer_name=\"$printer\"}",
       "legendFormat": "Y"
      },
      {
       "expr": "prusa_einsy_axis_z{printer_name=\"$printer\"}",
       "legendFormat": "Z"
      }
     ]
    },
    {
     "title": "Prusa Link ver",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_einsy_version{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_server}}"
      }
     ]
    },
    {
     "title": "Printer API ver",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_api)(prusa_einsy_info{printer_name=\"$printer\"})",
       "legendFormat": "{{printer_api}}"
      }
     ]
    },
    {
     "title": "Printer Link name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(prusa_einsy_info{printer_name=\"$printer\"}) by (printer_link_name)",
       "legendFormat": "{{printer_link_name}}"
      }
     ]
    },
    {
     "title": "IP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_einsy_version{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_address}}"
      }
     ]
    },
    {
     "title": "Number of files",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_einsy_files{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_storage}}"
      }
     ]
    },
    {
     "title": "Printer SN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_sn)(prusa_einsy_info{printer_name=\"$printer\"})",
       "legendFormat": "{{printer_sn}}"
      }
     ]
    },
    {
     "title": "Farm mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max (prusa_einsy_farm_mode{printer_name=\"$printer\"}) by (printer)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Target temp success",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_einsy_nozzle_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_einsy_nozzle_target_temperature{printer_name=\"$printer\"})",
       "legendFormat": "Nozzle"
      },
      {
       "expr": "max by (printer_name)(prusa_einsy_bed_temperature{printer_name=\"$printer\"}) / max by (printer_name)(prusa_einsy_bed_target_temperature{printer_name=\"$printer\"})",
       "legendFormat": "Bed"
      }
     ]
    },
    {
     "title": "Filepath",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max by (printer_job_path)(prusa_einsy_material{printer_name=\"$printer\", printer_job_path!=\"\"})",
       "legendFormat": "{{printer_job_path}}"
      }
     ]
    },
    {
     "title": "Z Height in time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_einsy_z_height{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Printing progress in time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_einsy_printing_progress{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}