{
 "title": "Legacy / Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_legacy_z_height, printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_nozzle_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_legacy_bed_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    }
   ]
  },
  {
   "title": "Printing progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Actual printing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_print_time{printer_name=\"$printer\"} )",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printing time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_printing_time_remaining{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_z_height{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_model)(prusa_legacy_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_model}}"
    }
   ]
  },
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_address)(prusa_legacy_printing{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  { "title": "Printer metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Name of printed file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_legacy_printing{printer_name=\"$printer\"} == 1",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printer speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_print_speed{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_printing{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Z Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_z_height{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chosen Filament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_filament)(prusa_legacy_material{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_bed_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_legacy_bed_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Nozzle Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_nozzle_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - actual"
    },
    {
     "expr": "max by (printer_name)(prusa_legacy_nozzle_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}} - target"
    }
   ]
  },
  {
   "title": "Z Height in time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_z_height{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing progress in time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_legacy_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}