{
 "title": "Prusa Overview Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of printers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (prusa_einsy_status)  + count (prusa_buddy_status)",
     "legendFormat": "{{printer_model}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (prusa_einsy_status) by (printer_model)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count (prusa_buddy_status) by (printer_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printers status",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max by (printer_name, printer_model)(prusa_einsy_status) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (printer_name, printer_model)(prusa_buddy_status) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (printer_name,printer_state)(prusa_einsy_status)",
     "legendFormat": "{{printer_name}}"
    },
    {
     "expr": "max by (printer_name)(prusa_buddy_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}