{
 "title": "PrusaLink Dashboard",
 "description": "This is dashboard for monitoring Prusa 3D printers with use of pubeldev/prusa_exporter. Uses only PrusaLink metrics",
 "time": { "from": "2024-02-27T21:22:33.080Z", "to": "2024-02-27T23:54:43.054Z" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_info,printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" },
   {
    "name": "printer_address",
    "query": {
     "query": "label_values(prusa_info{printer_name=\"$printer\"},printer_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_tool_temp{printer_name=\"$printer\"}) ",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_tool_temp_target{printer_name=\"$printer\"})",
     "legendFormat": "Target nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_bed_temp{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_bed_temp_target{printer_name=\"$printer\"})",
     "legendFormat": "Target bed"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name, fan)(prusa_fan_speed{printer_name=\"$printer\"})",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Nozzle size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_nozzle_size{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printing progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing_progress{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Actual printing time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_print_time{printer_name=\"$printer\"} )",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Printing time remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_printing_time_remaining{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_address}}"
    }
   ]
  },
  {
   "title": "Loaded filament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_filament)(prusa_material{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Name of printed file",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_status{printer_name=\"$printer\"} == 4",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Z Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_axis{printer_axis=\"z\", printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pritner_state, printer_name)(prusa_status{printer_name=\"$printer\"}) ",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_info{printer_name=\"$printer\"}) by (printer_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_info{printer_name=\"$printer\"})",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_print_speed_ratio{printer_name=\"$printer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle temperatures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_tool_temp{printer_name=\"$printer\"}) ",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "max by (printer_name)(prusa_tool_temp_target{printer_name=\"$printer\"})",
     "legendFormat": "Target nozzle"
    }
   ]
  },
  {
   "title": "Bed temperatures",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_bed_temp{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_bed_temp_target{printer_name=\"$printer\"})",
     "legendFormat": "Target bed"
    }
   ]
  },
  {
   "title": "Printer Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target temp success",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name, tool)(prusa_tool_temp{printer_name=\"$printer\"}) / max by (printer_name,tool)(prusa_tool_temp_target{printer_name=\"$printer\"}) ",
       "legendFormat": "Nozzle"
      },
      {
       "expr": "max by (printer_name)(prusa_bed_temp{printer_name=\"$printer\"}) / max by (printer_name)(prusa_bed_temp_target{printer_name=\"$printer\"}) ",
       "legendFormat": "Bed"
      }
     ]
    },
    {
     "title": "IP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_address)(prusa_info{printer_name=\"$printer\"})",
       "legendFormat": "{{printer_address}}"
      }
     ]
    },
    {
     "title": "Axis positions",
     "type": "stat",
     "description": "While printing printer returns unfortunately 0 but z axis",
     "gridPos": { "h": 4, "w": 9, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name, printer_axis)(prusa_axis{printer_name=\"$printer\"}) ",
       "legendFormat": "{{printer_axis}}"
      }
     ]
    },
    {
     "title": "PrusaLink type",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (version_text)(prusa_info{printer_name=\"$printer\"})",
       "legendFormat": "{{version_text}}"
      }
     ]
    },
    {
     "title": "Prusa Link ver",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (server_version)(prusa_info{printer_name=\"$printer\"})",
       "legendFormat": "{{server_version}}"
      }
     ]
    },
    {
     "title": "Number of files",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prusa_files{printer_name=\"$printer\"}",
       "legendFormat": "{{printer_storage}}"
      }
     ]
    },
    {
     "title": "MMU status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 2, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_mmu{printer_name=\"$printer\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filepath",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 5, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "max by (printer_job_path)(prusa_material{printer_name=\"$printer\", printer_job_path!=\"\"})",
       "legendFormat": "{{printer_job_path}}"
      }
     ]
    },
    {
     "title": "Printing progress in time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (printer_name)(prusa_printing_progress{printer_name=\"$printer\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fan speeds",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "max by (printer_name, fan)(prusa_fan_speed{printer_name=\"$printer\"})",
       "legendFormat": "{{fan}}"
      }
     ]
    },
    {
     "title": "Z Height in time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "max by (printer_name, printer_axis)(prusa_axis{printer_name=\"$printer\"})",
       "legendFormat": "{{printer_axis}}"
      }
     ]
    }
   ]
  }
 ]
}