{
 "title": "Prusa SL Dashboard",
 "description": "This is dashboard for monitoring Prusa resin 3D printers with use of pubeldev/prusa_exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_sl_status,printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" },
   {
    "name": "printer_address",
    "query": {
     "query": "label_values(prusa_sl_info{printer_name=\"$printer\"},printer_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_tool_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Tool"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_tool_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target tool"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_chamber_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Chamber"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_chamber_target_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Target chamber"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_bed_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_bed_target_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Target bed"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_cpu_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Tool"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_fan_blower{printer_name=\"$printer\"})",
     "legendFormat": "Blower fan"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_fan_rear{printer_name=\"$printer\"})",
     "legendFormat": "Rear fan"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_fan_uv{printer_name=\"$printer\"})",
     "legendFormat": "UV fan"
    }
   ]
  },
  {
   "title": "Printer type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_sl_version{printer_name=\"$printer\"}) by (printer_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_sl_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pritner_state, printer_name)(prusa_sl_status{printer_name=\"$printer\"}) ",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "API ver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_sl_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_api}}"
    }
   ]
  },
  {
   "title": "Link type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_sl_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_text}}"
    }
   ]
  },
  {
   "title": "Link ver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_sl_version{printer_name=\"$printer\"}",
     "legendFormat": "{{printer_server}}"
    }
   ]
  },
  {
   "title": "Tool temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_tool_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Tool"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_tool_target_temperature{printer_name=\"$printer\"})",
     "legendFormat": "Target tool"
    }
   ]
  },
  {
   "title": "Chamber temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_chamber_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Chamber"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_chamber_target_temperature{printer_name=\"$printer\"})     ",
     "legendFormat": "Target chamber"
    }
   ]
  },
  {
   "title": "Bed temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_sl_bed_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Bed"
    },
    {
     "expr": "max by (printer_name)(prusa_sl_bed_target_temperature{printer_name=\"$printer\"}) ",
     "legendFormat": "Target bed"
    }
   ]
  }
 ]
}