{
 "title": "Prusa Syslog Dashboard",
 "description": "This is dashboard for monitoring Prusa Buddy based 3D printers that expose metrics via Syslog with use of pubeldev/prusa_exporter",
 "time": { "from": "2024-03-04T21:11:56.756Z", "to": "2024-03-04T23:55:05.426Z" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_info{printer_address=\"$printer_ip\"},printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" },
   {
    "name": "printer_mac",
    "query": {
     "query": "label_values(prusa_cpu_usage_ratio,mac)"
    }
   },
   {
    "name": "printer_ip",
    "query": {
     "query": "label_values(prusa_current{mac=\"$printer_mac\"},ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Printer Detail - SYSLOG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\"noz.*|.*bed.*\"}) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (mac)(prusa_up_syslog{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Extruder",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (printer_name) (prusa_active_extruder{printer_name=\"$printer\"}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heater Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_heater_enabled{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjustment of Z Axis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac) (prusa_axis_z_adjustment{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buddy BOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_buddy_bom{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buddy revision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prusa_buddy_revision{mac=\"$printer_mac\"})",
     "legendFormat": "{{buddy_bom}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_cpu_usage_ratio{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- max by (mac)(prusa_heap_free{mac=\"$printer_mac\"}) / max by (mac)(prusa_heap_total{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (device, rail)(prusa_voltage{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\"noz.*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bed temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\".*bed.*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_cpu_usage_ratio{mac=\"$printer_mac\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_heap_total{mac=\"$printer_mac\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (mac)(prusa_heap_total{mac=\"$printer_mac\"}) - max by (mac)(prusa_heap_free{mac=\"$printer_mac\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (device,rail)(prusa_current{mac=\"$printer_mac\"})",
     "legendFormat": "{{device}} {{rail}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "max by (device, rail)(prusa_voltage{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature detail",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Loadcell data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (mac) (prusa_loadcell{mac=\"$printer_mac\"})",
     "legendFormat": "Value"
    },
    {
     "expr": "max by (mac) (prusa_loadcell_age{mac=\"$printer_mac\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (mac) (prusa_loadcell_scale{mac=\"$printer_mac\"})",
     "legendFormat": "Scale"
    }
   ]
  },
  {
   "title": "Points dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_points_dropped{mac=\"$printer_mac\"})",
     "legendFormat": "Dropped points"
    }
   ]
  },
  {
   "title": "Media prefetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_media_prefetched_bytes{mac=\"$printer_mac\"})",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Bedlet regulation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_d{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - d"
    },
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_i{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - i"
    },
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_tc{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - tc"
    }
   ]
  },
  {
   "title": "Stepper position",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"x\"})",
     "legendFormat": "{{Axis}}"
    },
    {
     "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"y\"})",
     "legendFormat": "{{Axis}}"
    },
    {
     "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"z\"})",
     "legendFormat": "{{Axis}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "avg by (device)(prusa_pwm{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dwarf fast refresh delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (mac)(prusa_dwarf_fast_refresh_delay{mac=\"$printer_mac\"})",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}