{
 "title": "Prusa Syslog Dashboard",
 "description": "This is dashboard for monitoring Prusa Buddy based 3D printers that expose metrics via Syslog with use of pubeldev/prusa_exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "printer",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_info{printer_address=\"$printer_ip\"},printer_name)"
    }
   },
   { "name": "ds_prom", "label": "Datasource", "query": "prometheus" },
   {
    "name": "printer_mac",
    "label": "Printer MAC",
    "query": {
     "query": "label_values(prusa_cpu_usage_ratio,mac)"
    }
   },
   {
    "name": "printer_ip",
    "label": "Printer IP",
    "query": {
     "query": "label_values(prusa_current{mac=\"$printer_mac\"},ip)"
    }
   },
   {
    "name": "proc_id",
    "label": "Log proc_id",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Log severity",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Log Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Extruder",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac) (prusa_active_extruder{mac=\"$printer_mac\"}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heater Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_heater_enabled{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_cpu_usage_ratio{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- max by (mac)(prusa_heap_free{mac=\"$printer_mac\"}) / max by (mac)(prusa_heap_total{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (device, rail)(prusa_voltage{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buddy revision",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_buddy_revision{mac=\"$printer_mac\"})",
     "legendFormat": "{{buddy_bom}}"
    }
   ]
  },
  {
   "title": "Buddy BOM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_buddy_bom{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (mac)(prusa_up_syslog{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded filament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "max by(filament)(prusa_filament{mac=\"$printer_mac\"})",
     "legendFormat": "{{filament}}"
    }
   ]
  },
  {
   "title": "Overcurrent detected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (device)(prusa_overcurrent{mac=\"10:9c:70:2c:da:8\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjustment of Z Axis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac) (prusa_axis_z_adjustment{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(prusa_buddy_fw{mac=\"$printer_mac\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Printing file name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (filename)(prusa_print_filename{mac=\"$printer_mac\"})",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Average power consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "-1*( sum (prusa_voltage{mac=\"$printer_mac\", device=\"bed\"}) * max(prusa_current{mac=\"$printer_mac\", device=\"inp\"}) / 1000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(prusa_current{mac=\"$printer_mac\", device!~\"bedlet.*\", rail!=\"5V\"}) * max (prusa_voltage{mac=\"$printer_mac\", rail=\"24V\"}) + (sum(prusa_current{mac=\"$printer_mac\", rail=\"5V\"}) * max(prusa_voltage{mac=\"$printer_mac\", rail=\"5V\"}))) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\"noz.*|.*bed.*\"}) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "max by (device, rail)(prusa_voltage{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "-1*( sum (prusa_voltage{mac=\"$printer_mac\", device=\"bed\"}) * max(prusa_current{mac=\"$printer_mac\", device=\"inp\"}) / 1000)",
     "legendFormat": "Input"
    },
    {
     "expr": "(sum(prusa_current{mac=\"$printer_mac\", device!~\"bedlet.*\", rail!=\"5V\"}) * max (prusa_voltage{mac=\"$printer_mac\", rail=\"24V\"}) + (sum(prusa_current{mac=\"$printer_mac\", rail=\"5V\"}) * max(prusa_voltage{mac=\"$printer_mac\", rail=\"5V\"}))) / 1000",
     "legendFormat": "Input"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "max by (device,rail)(prusa_current{mac=\"$printer_mac\", device!~\"bedlet.*\"})",
     "legendFormat": "{{device}} {{rail}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_heap_total{mac=\"$printer_mac\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (mac)(prusa_heap_total{mac=\"$printer_mac\"}) - max by (mac)(prusa_heap_free{mac=\"$printer_mac\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_cpu_usage_ratio{mac=\"$printer_mac\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\"noz.*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bed temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\", device=~\".*bed.*\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature detail",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (mac, device) (prusa_temp{mac=\"$printer_mac\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Loadcell data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (mac) (prusa_loadcell{mac=\"$printer_mac\"})",
     "legendFormat": "Value"
    },
    {
     "expr": "max by (mac) (prusa_loadcell_age{mac=\"$printer_mac\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (mac) (prusa_loadcell_scale{mac=\"$printer_mac\"})",
     "legendFormat": "Scale"
    }
   ]
  },
  {
   "title": "Points dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_points_dropped{mac=\"$printer_mac\"})",
     "legendFormat": "Dropped points"
    }
   ]
  },
  {
   "title": "Media prefetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (mac)(prusa_media_prefetched_bytes{mac=\"$printer_mac\"})",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Bedlet regulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_d{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - d"
    },
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_i{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - i"
    },
    {
     "expr": "max by (bedlet)(prusa_bedlet_regulation_tc{mac=\"$printer_mac\"})",
     "legendFormat": "{{bedlet}} - tc"
    }
   ]
  },
  {
   "title": "PWM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "avg by (device)(prusa_pwm{mac=\"$printer_mac\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dwarf fast refresh delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (mac)(prusa_dwarf_fast_refresh_delay{mac=\"$printer_mac\"})",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (device)(rate(prusa_network_in_total{mac=\"$printer_mac\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - In"
    },
    {
     "expr": "sum by (device)(rate(prusa_network_out_total{mac=\"$printer_mac\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - Out"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Printer Logs Count by proc_id",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(({hostname=\"$printer_mac\"})[$__range])) by (proc_id)",
       "legendFormat": "{{proc_id}}"
      }
     ]
    },
    {
     "title": "Printer Logs Count by severity",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time(({hostname=\"$printer_mac\"})[$__range])) by (severity)",
       "legendFormat": "{{proc_id}}"
      }
     ]
    },
    {
     "title": "Count over time",
     "type": "timeseries",
     "description": "Total Count of log lines in the specified time range",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time(({hostname=\"$printer_mac\", proc_id=~\"$proc_id\", severity=~\"$severity\"} |~ \"(?i)$searchable_pattern\"  )[$__range]))",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Printer Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{hostname=\"$printer_mac\", proc_id=~\"$proc_id\", severity=~\"$severity\"} |~ \"(?i)$searchable_pattern\" "
      }
     ]
    }
   ]
  },
  {
   "title": "Experimental",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stepper position",
     "type": "grafana-xyzchart-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"x\"})",
       "legendFormat": "{{Axis}}"
      },
      {
       "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"y\"})",
       "legendFormat": "{{Axis}}"
      },
      {
       "expr": "avg by (mac, axis)(prusa_stepper_pos{mac=\"$printer_mac\", axis=\"z\"})",
       "legendFormat": "{{Axis}}"
      }
     ]
    },
    {
     "title": "Bed PWM",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 16, "w": 7, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "prusa_pwm{device=~\"bedlet.*\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Processed gcodes",
     "type": "table",
     "gridPos": { "h": 16, "w": 5, "x": 19, "y": 12 },
     "targets": [
      {
       "expr": "prusa_gcode{mac=\"$printer_mac\"}",
       "legendFormat": "{{gcode}}"
      }
     ]
    }
   ]
  }
 ]
}