{
 "title": "Prusa Metrics TV",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ip", "label": "Printer", "query": { "query": "label_values(ip)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Welcome!",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(vector(0), \"fosdem\", \"https://149753425.v2.pressablecdn.com/wp-content/uploads/2024/12/fosdem-logo.jpg\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_name) (prusa_info{printer_address=\"$ip\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printer Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_model) (prusa_info{printer_address=\"$ip\"})",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_state) (prusa_status_info{printer_address=\"$ip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prusa_printing_progress_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_time_remaining_seconds{printer_address=\"$ip\", printer_job_name!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "prusa_exporter", "type": "betatech-qrcode-panel", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Temperature - Nozzle",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "prusa_temp_noz{ip=\"$ip\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "prusa_ttemp_noz{ip=\"$ip\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Temperature - Heatbed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "prusa_temp_bed_v{ip=\"$ip\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "prusa_ttemp_bed_v{ip=\"$ip\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Printed File",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "prusa_job_image{printer_address=\"$ip\"}",
     "legendFormat": "{{printer_job_path}}"
    }
   ]
  },
  {
   "title": "Temeprature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_temp_noz{ip=\"$ip\"}",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "prusa_temp_bed_v{ip=\"$ip\"}",
     "legendFormat": "Heatbed"
    },
    {
     "expr": "prusa_temp_mcu_v{ip=\"$ip\"}",
     "legendFormat": "MCU"
    },
    {
     "expr": "prusa_temp_hbr{ip=\"$ip\"}",
     "legendFormat": "Heatbreak"
    },
    {
     "expr": "prusa_chamber_temp_v{ip=\"$ip\"}",
     "legendFormat": "Chamber"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_status_info{printer_address=\"$ip\"} == 4",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Loadcell",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "prusa_loadcell_value_v{ip=\"$ip\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Power consumption (experimental)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(prusa_curr_inp_v{ip=\"$ip\"}*(-1))* 24",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_filament) (prusa_material_info{printer_address=\"$ip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_print_speed_ratio{printer_address=\"192.168.20.50\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_fan_speed_rpm{printer_address=\"$ip\"}",
     "legendFormat": "{{fan}} fan"
    }
   ]
  },
  {
   "title": "Nozzle Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_nozzle_size_meters{printer_address=\"$ip\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "MMU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_mmu{printer_address=\"$ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_volt_nozz_v{ip=\"$ip\"}",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "prusa_volt_bed_v{ip=\"$ip\"}",
     "legendFormat": "Heatbed"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prusa_eth_out_sent{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "Ethernet Out"
    },
    {
     "expr": "rate(prusa_eth_in_recv{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "Ethernet In"
    }
   ]
  },
  { "title": "DISCLAIMER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "This whole setup and especially prusa_exporter is considered experimental and is considered more of a PoC than a final product! Check it out by scanning the QR code or asking anyone at the booth. Thank you and enjoy FOSDEM 2025!"
   }
  }
 ]
}